server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # ✅ React SPA
    location / {
        try_files $uri /index.html;
    }

    # ✅ API proxy
    location /api/ {
        proxy_pass 3

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    # ✅ WebSocket
    location /ws/ {
        proxy_pass https://workspace.hedej.lge.com/project/be-audio-test/seokmin-koh/proxy/8000/api/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host $host;
    }
}